=== umccr/orcabus/docs/schemas/data/bclconvertmanager/PayloadDataSucceeded.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/data/bclconvertmanager/PayloadDataSucceeded.schema.json",
  "description": "Data schema for orcabus.bclconvertmanager@PayloadDataSucceeded",
  "title": "PayloadDataSucceeded",
  "type": "object",
  "required": [
    "projectId",
    "analysisId",
    "userReference",
    "timeCreated",
    "timeModified",
    "pipelineId",
    "pipelineCode",
    "pipelineDescription",
    "pipelineUrn",
    "instrumentRunId",
    "basespaceRunId",
    "samplesheetB64gz"
  ],
  "properties": {
    "projectId": {
      "type": "string"
    },
    "analysisId": {
      "type": "string"
    },
    "userReference": {
      "type": "string"
    },
    "timeCreated": {
      "type": "string",
      "format": "date-time"
    },
    "timeModified": {
      "type": "string",
      "format": "date-time"
    },
    "pipelineId": {
      "type": "string"
    },
    "pipelineCode": {
      "type": "string"
    },
    "pipelineDescription": {
      "type": "string"
    },
    "pipelineUrn": {
      "type": "string"
    },
    "instrumentRunId": {
      "type": "string"
    },
    "basespaceRunId": {
      "type": "string"
    },
    "samplesheetB64gz": {
      "type": "string"
    }
  }
}

=== umccr/orcabus/docs/schemas/data/bclconvertmanager/example/PayloadDataSucceeded__example1.json
{
  "projectId": "valid_project_id",
  "analysisId": "valid_payload_id",
  "userReference": "123456_A1234_0000_TestingPattern",
  "timeCreated": "2024-01-01T00:11:35Z",
  "timeModified": "2024-01-01T01:24:29Z",
  "pipelineId": "valid_pipeline_id",
  "pipelineCode": "BclConvert v0_0_0",
  "pipelineDescription": "BclConvert pipeline.",
  "pipelineUrn": "urn:ilmn:ica:pipeline:123456-abcd-efghi-1234-acdefg1234a#BclConvert_v0_0_0",
  "instrumentRunId": "12345_A12345_1234_ABCDE12345",
  "basespaceRunId": "1234567",
  "samplesheetB64gz": "H4sIAFGBVWYC/9VaUW+jOBD+Kyvu9VqBgST0njhWh046..."
}
