=== umccr/orcabus/docs/schemas/events/workflowmanager/WorkflowRunStateChange.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/workflowmanager/WorkflowRunStateChange.schema.json",
  "description": "EventBridge custom event schema for orcabus.workflowmanager@WorkflowRunStateChange",
  "title": "AWSEvent",
  "type": "object",
  "required": [
    "detail-type",
    "detail",
    "source"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/WorkflowRunStateChange"
    }
  },
  "definitions": {
    "WorkflowRunStateChange": {
      "type": "object",
      "required": [
        "portalRunId",
        "timestamp",
        "status",
        "workflowName",
        "workflowVersion",
        "workflowRunName"
      ],
      "properties": {
        "portalRunId": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "status": {
          "type": "string"
        },
        "workflowName": {
          "type": "string"
        },
        "workflowVersion": {
          "type": "string"
        },
        "workflowRunName": {
          "type": "string"
        },
        "linkedLibraries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LibraryRecord"
          }
        },
        "payload": {
          "$ref": "#/definitions/Payload"
        }
      }
    },
    "LibraryRecord": {
      "type": "object",
      "required": [
        "libraryId",
        "orcabusId"
      ],
      "properties": {
        "libraryId": {
          "type": "string"
        },
        "orcabusId": {
          "type": "string"
        }
      }
    },
    "Payload": {
      "type": "object",
      "required": [
        "refId",
        "version",
        "data"
      ],
      "properties": {
        "refId": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "data": {
          "type": "object"
        }
      }
    }
  }
}

=== umccr/orcabus/docs/schemas/events/workflowmanager/example/WRSC__example2.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "portalRunId": "202405012397gatc",
    "timestamp": "2025-05-01T09:25:44Z",
    "status": "RUNNING",
    "workflowName": "<fill-by-workflow-manager> e.g. bssh_icav2_fastq_copy",
    "workflowVersion": "<fill-by-workflow-manager> e.g. 1.2.3",
    "workflowRunName": "<fill-by-workflow-manager> e.g. 540424_A01001_0193_BBBBMMDRX5 FASTQ Copy"
  }
}

=== umccr/orcabus/docs/schemas/events/workflowmanager/example/WRSC__example1.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "portalRunId": "202405012397gatc",
    "timestamp": "2025-05-01T09:25:44Z",
    "status": "READY",
    "workflowName": "<fill-by-workflow-manager> e.g. bssh_icav2_fastq_copy",
    "workflowVersion": "<fill-by-workflow-manager> e.g. 1.2.3",
    "workflowRunName": "<fill-by-workflow-manager> e.g. 540424_A01001_0193_BBBBMMDRX5 FASTQ Copy",
    "linkedLibraries": [
      {
        "libraryId": "L000001",
        "orcabusId": "lib.01J5M2J44HFJ9424G7074NKTGN"
      },
      {
        "libraryId": "L000002",
        "orcabusId": "lib.01J5M2JFE1JPYV62RYQEG99CP5"
      }
    ],
    "payload": {
      "refId": "<fill-by-workflow-manager> e.g. <uuid>",
      "version": "0.1.0",
      "data": {
        "projectId": "bxxxxxxxx-dxxx-4xxxx-adcc-xxxxxxxxx",
        "analysisId": "12345678-238c-4200-b632-d5dd8c8db94a",
        "outputUriPrefix": "icav2://12345678-32d3-4c76-a324-c6a85dae87b5/ilmn_primary/"
      }
    }
  }
}

=== umccr/orcabus/lib/workload/stateless/stacks/fmannotator/fixtures/event_succeeded.json
{
  "version": "0",
  "id": "ae02404d-9965-e3c7-2343-89cb5d46fedf",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.workflowmanager",
  "account": "123456789012",
  "time": "2024-09-02T00:00:01Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "portalRunId": "202409021221e6e6",
    "workflowName": "wts",
    "workflowRunName": "umccr--automated--wts--4-2-4--202409021221e6e6",
    "workflowVersion": "4.2.4",
    "timestamp": "2024-09-02T00:00:00Z",
    "status": "SUCCEEDED"
  }
}

=== umccr/orcabus/docs/schemas/events/executionservice/example/WRSC__example2.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "WorkflowRunStateChange",
  "source": "orcabus.bclconvertmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "portalRunId": "202405012397gatc",
    "executionId": "<e.g. ICAv2 analysis id>",
    "timestamp": "2026-05-01T09:25:44Z",
    "status": "RUNNING",
    "workflowName": "BclConvert",
    "workflowVersion": "4.2.7",
    "workflowRunName": "540424_A01001_0193_BBBBMMDRX5"
  }
}
