=== umccr/orcabus/docs/schemas/events/sequencerunmanager/SequenceRunSampleSheetChange.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/sequencerunmanager/SequenceRunSampleSheetChange.schema.json",
    "description": "EventBridge custom event schema for orcabus.sequencerunmanager@SequenceRunSampleSheetChange",
    "title": "AWSEvent",
    "type": "object",
    "required": [
        "detail-type",
        "detail",
        "source"
    ],
    "properties": {
        "id": {
            "type": "string"
        },
        "region": {
            "type": "string"
        },
        "resources": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "source": {
            "type": "string"
        },
        "time": {
            "type": "string",
            "format": "date-time"
        },
        "version": {
            "type": "string"
        },
        "account": {
            "type": "string"
        },
        "detail-type": {
            "type": "string"
        },
        "detail": {
            "$ref": "#/definitions/SequenceRunSampleSheetChange"
        }
    },
    "definitions": {
        "SequenceRunSampleSheetChange": {
            "type": "object",
            "required": [
                "instrumentRunId",
                "sequenceRunId",
                "sequenceRunOrcabusId",
                "timeStamp",
                "sampleSheetName",
                "samplesheetbase64gz"
            ],
            "properties": {
                "instrumentRunId": {
                    "type": "string"
                },
                "sequenceRunId": {
                    "type": "string"
                },
                "sequenceRunOrcabusId": {
                    "type": "string"
                },
                "timeStamp": {
                    "type": "string"
                },
                "sampleSheetName": {
                    "type": "string"
                },
                "samplesheetbase64gz": {
                    "type": "string"
                }
            }
        }
    }
}

=== umccr/orcabus/docs/schemas/events/sequencerunmanager/example/SRSSC.json
{
    "version": "0",
    "id": "12345678-90ab-cdef-1234-567890abcdef",
    "detail-type": "SequenceRunSampleSheetChange",
    "source": "orcabus.sequencerunmanager",
    "account": "000000000000",
    "time": "2025-03-00T00:00:00Z",
    "region": "ap-southeast-2",
    "resources": [],
    "detail": {
        "instrumentRunId": "123456_A7890_1234_ABCDEFGH",
        "sequenceRunId": "r.1234567890abcdefghijklmn",
        "sequenceRunOrcabusId": "seq.1234567890ABCDEFGHIJKLMN",
        "timeStamp": "2025-03-01T00:00:00.123456Z",
        "sampleSheetName": "sampleSheet_v2.csv",
        "samplesheetbase64gz": "base64_encoded_samplesheet........"
    }
}
