=== umccr/orcabus/docs/schemas/events/metadatamanager/MetadataStateChange.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/workflowmanager/WorkflowRunStateChange.schema.json",
  "description": "EventBridge custom event schema for orcabus.metadatamanager@MetadataStateChange",
  "title": "AWSEvent",
  "type": "object",
  "required": [
    "detail-type",
    "detail",
    "source"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "const": "orcabus.metadatamanager"
    },
    "time": {
      "type": "string",
      "format": "date-time"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "const": "MetadataStateChange"
    },
    "detail": {
      "$ref": "#/definitions/MetadataStateChange"
    }
  },
  "definitions": {
    "MetadataStateChange": {
      "type": "object",
      "required": [
        "model",
        "action",
        "data"
      ],
      "properties": {
        "model": {
          "type": "string",
          "enum": [
            "LIBRARY",
            "SPECIMEN",
            "SUBJECT"
          ]
        },
        "action": {
          "type": "string",
          "enum": [
            "CREATE",
            "UPDATE",
            "DELETE"
          ]
        },
        "data": {
          "type": "object"
        }
      }
    }
  }
}

=== umccr/orcabus/docs/schemas/events/metadatamanager/example/MSC__example2.json
{
  "version": "0",
  "id": "f71bbbbb-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "MetadataStateChange",
  "source": "orcabus.metadatamanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "action": "DELETE",
    "model": "LIBRARY",
    "refId": "lib.01J8GNBB7YK8RCVFGXSBV4ZKST",
    "data": {
      "orcabusId": "lib.01J8GNBB7YK8RCVFGXSBV4ZKST",
      "libraryId": "L10001",
      "phenotype": "normal",
      "workflow": "research",
      "quality": "poor",
      "type": "WTS",
      "assay": "ctTSO",
      "coverage": 120.0,
      "sample": "smp.01J8GNBB67HGG3G17QA5QP98TE",
      "subject": "sbj.01J8GNBB59GR0KMTNR0BT3F31V"
    }
  }
}
